prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl:  <http://www.w3.org/2002/07/owl#>
prefix bibo:  <http://purl.org/ontology/bibo/>
select distinct (str(?status_label_raw) as ?status_label)
where { ?s a bibo:DocumentStatus ;
rdfs:label ?status_label_raw }
order by ?status_label
